forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

mod 'apt',
  :git => 'https://github.com/puppetlabs/puppetlabs-apt.git'

mod 'puppet-nginx',
  :git => 'https://github.com/jfryman/puppet-nginx.git'
